import { useState } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { BlockPicker, handleChangeComplete } from 'react-color';

const colors = ['#5697BF', '#73BCD9', '#C9E7F2'];

export default function Home() {
  const aColor = '#5697BF';
  const [color, setColor] = useState('#ffffff');
  // const [bgColor, setBgColor] = useState('#000000');
  handleChangeComplete = (color, event) => {
    setColor(color);
    // setBgColor(color.hex);
  };
  console.log({BlockPicker});
  return (
    <div className={styles.container}>
      <Head>
        <title>ColorSensedle</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <div style={{backgroundColor: `${bgColor}`}}> */}
      <div style={{backgroundColor: `${aColor}`}}>
        <main className={styles.main}>
          <BlockPicker
            color={color}
            colors={colors}
            onChangeComplete={ handleChangeComplete }
            style={{borderRadius: '8px'}}
          />
        </main>
      </div>
    </div>
  )
}
